spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: hunter
    password: 198105
    listener:
      simple:
        # 重试达到最大次数后，Spring会返回reject，消息会被丢弃
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
  mail:
    host: smtp.qq.com
    username: 1981053231@qq.com
    password: ugkwvwcgxtmhcecc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        default-encoding: UTF-8
eureka:
  client:
    enabled: false



